<?php
use Mageplaza\BetterMaintenance\Helper\Data;

/**
 * @var \Mageplaza\BetterMaintenance\Block\Comingsoon $block ;
 */

$helper              = $this->helper(Data::class);
$subscribeLabel      = $helper->getSubscribeSetting('subscribe_label');
$subscribeLabelColor = $helper->getSubscribeSetting('subscribe_label_color');
?>

<!--Multiple Image Background-->
<?php if ($helper->getComingSoonSetting('comingsoon_background') === 'multiple_images'
    && $block->getImageUrl($helper->getComingSoonSetting('comingsoon_background_multi_image'))): ?>
    <?php $listImagesUrl = implode(',',
        $block->getMultipleImagesUrl($helper->getMaintenanceSetting('maintenance_background_multi_image'))); ?>
    <style>
        .mpbettermaintenance-comingsoon-index {
            background-repeat: no-repeat;
            background-size: cover;
            transition-delay: 2s;
        }
    </style>
    <script>
        require([
            'jquery'
        ], function ($) {
            var images    = '<?= $listImagesUrl ?>';
            images        = images.split(',');
            var nextImage = 0;
            doSlideshow();

            function doSlideshow () {
                if (nextImage >= images.length) {
                    nextImage = 0;
                }
                $('.mpbettermaintenance-comingsoon-index')
                .fadeIn('slow', function () {
                    setTimeout(doSlideshow, 5000);
                }).css('background-image', 'url("' + images[nextImage++] + '")');
            }
        });
    </script>
<?php endif; ?>

<!--Single Image Background-->
<?php if ($helper->getComingSoonSetting('comingsoon_background') === 'image'
    && $block->getImageUrl($helper->getComingSoonSetting('comingsoon_background_image'))): ?>
    <style>
        .mpbettermaintenance-comingsoon-index {
            background-image: url("<?= $block->getImageUrl($helper->getComingSoonSetting('maintenance_background_image')) ?>");
            background-repeat: no-repeat;
            background-size: cover;
        }
    </style>
<?php endif; ?>

<!--Video Background-->
<?php if ($helper->getComingSoonSetting('maintenance_background') === 'video'
    && $block->getVideoUrl($helper->getComingSoonSetting('maintenance_background_video'))): ?>
    <video autoplay muted loop id="mpbm-video">
        <source src="<?= $block->getVideoUrl($helper->getComingSoonSetting('maintenance_background_video')) ?>"
                type="video/mp4">
    </video>
<?php endif; ?>
<div id="mpbm-<?= $helper->getComingsoonSetting('comingsoon_layout') ?>-column">
    <?php if (!empty($helper->getComingsoonSetting('comingsoon_logo'))): ?>
        <div id="mpbm-logo">
            <img src="<?= $block->getLogo($helper->getComingsoonSetting('comingsoon_logo')) ?>" alt="<?= __('Logo') ?>"
                 width="100">
        </div>
    <?php endif; ?>
    <div id="mpbm-page-title" class="mpbm-text">
        <h1 style="margin-bottom: 0"><?= $block->getPageTitle() ?></h1>
    </div>
    <div id="mpbm-page-description" class="mpbm-text">
        <h3><?= $block->getPageDescription() ?></h3>
    </div>

    <!--    Clock area-->
    <?php if ($helper->getClockSetting('clock_enabled')) : ?>
        <div id="mpbm-clock">
            <?= $this->getChildHtml('clock_countdown') ?>
        </div>
    <?php endif; ?>
    <!--    Subscribe area-->
    <?php if ($helper->getSubscribeSetting('subscribe_type') === 'email_form') : ?>
        <div id="mpbm-subscribe">
            <?php if ($helper->getSubscribeSetting('subscribe_label')): ?>
                <h4 style="color: <?= $subscribeLabelColor ?>"><?= $subscribeLabel ?></h4>
            <?php endif; ?>
            <?= $this->getChildHtml('subscribe') ?>
        </div>
    <?php elseif ($helper->getSubscribeSetting('subscribe_type') === 'register_form') : ?>
        <div id="mpbm-register">
            <?php if ($helper->getSubscribeSetting('subscribe_label')): ?>
                <h4 style="color: <?= $subscribeLabelColor ?>"><?= $subscribeLabel ?></h4>
            <?php endif; ?>
            <?= $this->getChildHtml('register') ?>
        </div>
    <?php endif; ?>

    <!--    Social area-->
    <?php if ($helper->getSocialSetting('social_enabled')): ?>
        <div id="mpbm-social-contact">
            <div id="mpbm-social-label" style="display: inline-block">
                <p><?= $block->getSocialLabel() ?></p>
            </div>
            <?php foreach ($block->getSocialList() as $value) : ?>

                <?php if ($value['link']) : ?>
                    <div class="mpbm-social-box" style="display: inline-block; vertical-align: middle">
                        <a href="<?= $value['link'] ?>" target="_blank">
                            <img src="<?= $value['img'] ?>" alt="" width="20">
                        </a>
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <?php if ($block->getBlockCms()) : ?>
        <div id="mpbm-footer-block">
            <?= $block->getBlockCms() ?>
        </div>
    <?php endif; ?>

</div>

<style>
    .mpbm-text {
        color: <?= $helper->getComingsoonSetting('comingsoon_color') ?>;
    }

    #mpbm-social-label {
        color: <?= $helper->getSocialSetting('social_label_color') ?>;
    }

    <?php if ($helper->getClockSetting('clock_template') === 'stack') : ?>
    .stack-txt1 {
        background: <?= $helper->getClockSetting('clock_inner_color') ?>;
    }
    <?php endif; ?>
</style>
