<?php
use Mageplaza\BetterMaintenance\Helper\Data;

/**
 * @var \Mageplaza\BetterMaintenance\Block\Comingsoon $block ;
 */

$helper = $this->helper(Data::class);

?>

<?php if ($helper->getComingSoonSetting('comingsoon_background') === 'image' && $block->getImageUrl($helper->getComingSoonSetting('comingsoon_background_image'))): ?>
    <style>
        .mpbettermaintenance-comingsoon-index {
            background-image: url("<?= $block->getImageUrl($helper->getComingSoonSetting('comingsoon_background_image')) ?>");
        }
    </style>
<?php endif; ?>
<div id="mpbm-<?= $helper->getComingsoonSetting('comingsoon_layout') ?>-column">
    <?php if (!empty($helper->getComingsoonSetting('comingsoon_logo'))): ?>
        <div id="mpbm-logo">
            <img src="<?= $block->getLogo($helper->getComingsoonSetting('comingsoon_logo')) ?>" alt="<?= __('Logo') ?>" width="100">
        </div>
    <?php endif; ?>
    <div id="mpbm-page-title" class="mpbm-text">
        <h1 style="margin-bottom: 0"><?= $block->getPageTitle() ?></h1>
    </div>
    <div id="mpbm-page-description" class="mpbm-text">
        <h3><?= $block->getPageDescription() ?></h3>
    </div>

    <!--    Clock area-->
    <?php if ($helper->getClockSetting('clock_enabled')) : ?>
        <div id="mpbm-clock">
            <?= $this->getChildHtml('clock_countdown') ?>
        </div>
    <?php endif; ?>
    <!--    Subscribe area-->
    <?php if ($helper->getSubscribeSetting('subscribe_type') === 'email_form') : ?>
        <div id="mpbm-subscribe">
            <?= $this->getChildHtml('subscribe') ?>
        </div>
    <?php elseif ($helper->getSubscribeSetting('subscribe_type') === 'register_form') : ?>
        <div id="mpbm-register">
            <?= $this->getChildHtml('register') ?>
        </div>
    <?php endif; ?>

    <!--    Social area-->
    <?php if ($helper->getSocialSetting('social_enabled')): ?>
        <div id="mpbm-social-contact">
            <div id="mpbm-social-label" style="display: inline-block">
                <p><?= $block->getSocialLabel() ?></p>
            </div>
            <?php foreach ($block->getSocialList() as $value) : ?>

                <?php if ($value['link']) : ?>
                    <div class="mpbm-social-box" style="display: inline-block; vertical-align: middle">
                        <a href="<?= $value['link'] ?>">
                            <img src="<?= $value['img'] ?>" alt="" width="20">
                        </a>
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <?php if ($block->getBlockCms()) : ?>
        <div id="mpbm-footer-block">
            <?= $block->getBlockCms() ?>
        </div>
    <?php endif; ?>

</div>

<style>
    #mpbm-subscribe {
        margin-bottom: 20px;
    }

    #mpbm-progress-bar {
        margin-bottom: 20px;
    }

    #mpbm-clock {
        margin: 20px auto;
    }

    #mpbm-logo {
        padding-top: 3%;
    }

    #mpbm-page-title {
        margin: 40px 0 0 0;
    }

    #mpbm-single-column {
        text-align: center;
    }

    #mpbm-wrapper li {
        list-style: none;
    }

    .mpbm-text {
        color: <?= $helper->getComingsoonSetting('comingsoon_color') ?>;
    }

    #mpbm-subscribe .block.newsletter {
        margin: auto;
    }
</style>
