<?php
use Mageplaza\BetterMaintenance\Helper\Data;

/**
 * @var \Mageplaza\BetterMaintenance\Block\Maintenance $block ;
 */

$helper = $this->helper(Data::class);
$listImagesUrl = implode(',', $block->getMultipleImagesUrl());
?>

<!--Multiple Image Background-->
<?php if ($helper->getMaintenanceSetting('maintenance_background') === 'multiple_images'
    && $block->getImageUrl($helper->getMaintenanceSetting('maintenance_background_multi_image'))): ?>
    <style>
        .mpbettermaintenance-maintenance-index {
            background-repeat: no-repeat;
            background-size: cover;
            transition-delay: 2s;
        }
    </style>
    <script>
        require([
            'jquery'
        ], function ($) {
            var images    = '<?= $listImagesUrl ?>';
            images        = images.split(',');
            var nextImage = 0;
            doSlideshow();

            function doSlideshow () {
                if (nextImage >= images.length) {
                    nextImage = 0;
                }
                $('.mpbettermaintenance-maintenance-index')
                .fadeIn('slow', function () {
                    setTimeout(doSlideshow, 5000);
                }).css('background-image', 'url("' + images[nextImage++] + '")');
            }
        });
    </script>
<?php endif; ?>

<!--Single Image Background-->
<?php if ($helper->getMaintenanceSetting('maintenance_background') === 'image'
    && $block->getImageUrl($helper->getMaintenanceSetting('maintenance_background_image'))): ?>
    <style>
        .mpbettermaintenance-maintenance-index {
            background-image: url("<?= $block->getImageUrl($helper->getMaintenanceSetting('maintenance_background_image')) ?>");
            background-repeat: no-repeat;
            background-size: cover;
        }
    </style>
<?php endif; ?>

<!--Video Background-->
<?php if ($helper->getMaintenanceSetting('maintenance_background') === 'video'
    && $block->getImageUrl($helper->getMaintenanceSetting('maintenance_background_video'))): ?>
    <video autoplay muted loop id="mpbm-video">
        <source src="<?= $block->getVideoUrl($helper->getMaintenanceSetting('maintenance_background_video')) ?>"
                type="video/mp4">
    </video>
<?php endif; ?>

<div id="mpbm-<?= $helper->getMaintenanceSetting('maintenance_layout') ?>-column">
    <?php if (!empty($helper->getMaintenanceSetting('maintenance_logo'))): ?>
        <div id="mpbm-logo">
            <img src="<?= $block->getLogo($helper->getMaintenanceSetting('maintenance_logo')) ?>"
                 alt="<?= __('Logo') ?>" width="100">
        </div>
    <?php endif; ?>
    <div id="mpbm-page-title" class="mpbm-text">
        <h1 style="margin-bottom: 0"><?= $block->getPageTitle() ?></h1>
    </div>
    <div id="mpbm-page-description" class="mpbm-text">
        <h3><?= $block->getPageDescription() ?></h3>
    </div>

    <!--    Clock area-->
    <?php if ($helper->getClockSetting('clock_enabled')) : ?>
        <div id="mpbm-clock">
            <?= $this->getChildHtml('clock_countdown') ?>
        </div>
    <?php endif; ?>
    <?php if ($helper->getMaintenanceSetting('maintenance_progress_enabled')): ?>
        <div id="mpbm-progress-bar">
            <div class="row">
                <div class="mp-md-6">
                    <div class="progress mp-md-3">
                        <div class="progress-bar" role="progressbar" aria-valuenow="<?= $block->getProgressValue() ?>"
                             aria-valuemin="0"
                             aria-valuemax="100"><?= $block->getProgressValue() ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php endif; ?>

    <!--    Subscribe area-->
    <?php if ($helper->getSubscribeSetting('subscribe_type') === 'email_form') : ?>
        <div id="mpbm-subscribe">
            <?= $this->getChildHtml('subscribe') ?>
        </div>
    <?php elseif ($helper->getSubscribeSetting('subscribe_type') === 'register_form') : ?>
        <div id="mpbm-register">
            <?= $this->getChildHtml('register') ?>
        </div>
    <?php endif; ?>

    <!--    Social area-->
    <?php if ($helper->getSocialSetting('social_enabled')): ?>
        <div id="mpbm-social-contact">
            <div id="mpbm-social-label" style="display: inline-block">
                <p><?= $block->getSocialLabel() ?></p>
            </div>
            <?php foreach ($block->getSocialList() as $value) : ?>

                <?php if ($value['link']) : ?>
                    <div class="mpbm-social-box" style="display: inline-block; vertical-align: middle">
                        <a href="<?= $value['link'] ?>">
                            <img src="<?= $value['img'] ?>" alt="<?= __('Social Logo') ?>" width="20">
                        </a>
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <?php if ($block->getBlockCms()) : ?>
        <div id="mpbm-footer-block">
            <?= $block->getBlockCms() ?>
        </div>
    <?php endif; ?>

</div>

<style>
    /*Single column*/
    #mpbm-single-column {
        text-align: center;
    }

    /*Double column left side*/
    #mpbm-double_left-column {
        text-align: center;
    }

    #mpbm-double_left-column .progress {
        margin: auto 0px;
    }

    #mpbm-double_left-column .simple-container {
        justify-content: left;
    }

    /*Double column*/

    #mpbm-video {
        position: fixed;
        z-index: -1;
        right: 0;
        bottom: 0;
        min-width: 100%;
        min-height: 100%;
    }

    #mpbm-subscribe {
        margin-bottom: 20px;
    }

    #mpbm-progress-bar {
        margin-bottom: 20px;
    }

    #mpbm-clock {
        margin: 20px auto;
    }

    #mpbm-logo {
        padding-top: 3%;
    }

    #mpbm-page-title {
        margin: 40px 0 0 0;
    }

    #mpbm-wrapper li {
        list-style: none;
    }

    .mpbm-text {
        color: <?= $helper->getMaintenanceSetting('maintenance_color') ?>;
    }

    #mpbm-subscribe .block.newsletter {
        margin: auto;
    }

    .progress {
        margin: auto;
        height: 45px;
        width: 40%;
        background: #F7F7F7;
        text-align: center;
        border-radius: 50px;
    }

    .progress-bar {
        height: 45px;
        font-size: 100%;
        font-weight: bold;
        border-radius: 50px;
        line-height: 45px;
        color: <?= $helper->getMaintenanceSetting('maintenance_progress_label_color') ?>;
        background-color: <?= $helper->getMaintenanceSetting('maintenance_progress_bar_color') ?>;
        width: 0;
    }
</style>
<script type="text/x-magento-init">
    {
        "*": {
            "Mageplaza_BetterMaintenance/js/progress/bar": {
                "progressLabel": "<?= $block->getProgressLabel() ?>"
            }
        }
    }

</script>
