<?php $data = $block->getFormData(); ?>

<!--Multiple Image Background-->
<?php if ($data['[maintenance_background]'] === 'multiple_images'): ?>
    <?php $listImagesUrl = implode(',', $block->getMultipleImagesUrl('maintenance_background_multi_image')); ?>
    <style>
        .mpbettermaintenance-maintenance-preview {
            background-repeat: no-repeat;
            background-size: cover;
            transition-delay: 2s;
        }
    </style>
    <script>
        require([
            'jquery'
        ], function ($) {
            var images    = '<?= $listImagesUrl ?>';
            images        = images.split(',');
            var nextImage = 0;
            doSlideshow();

            function doSlideshow () {
                if (nextImage >= images.length) {
                    nextImage = 0;
                }
                $('.mpbettermaintenance-maintenance-preview')
                .fadeIn('slow', function () {
                    setTimeout(doSlideshow, 5000);
                }).css('background-image', 'url("' + images[nextImage++] + '")');
            }
        });
    </script>
<?php endif; ?>

<!--Single Image Background-->
<?php if ($data['[maintenance_background]'] === 'image'
    && $block->getImageUrl($data['[maintenance_background_image]'])): ?>
    <style>
        .mpbettermaintenance-maintenance-preview {
            background-image: url("<?= $block->getImageUrl($data['[maintenance_background_image]']) ?>");
            background-repeat: no-repeat;
            background-size: cover;
        }
    </style>
<?php endif; ?>

<!--Video Background-->
<?php if ($data['[maintenance_background]'] === 'video'
    && $block->getVideoUrl($data['[maintenance_background_video]'])): ?>
    <video autoplay muted loop id="mpbm-video">
        <source src="<?= $block->getVideoUrl($data['[maintenance_background_video]']) ?>"
                type="video/mp4">
    </video>
<?php endif; ?>

<div id="mpbm-<?= $data['[maintenance_layout]'] ?>-column" class="mpbm-preview-wrapper">
    <?php if (!empty($data['[maintenance_logo]'])): ?>
        <div id="mpbm-logo">
            <img src="<?= $block->getLogo($data['[maintenance_logo]']) ?>"
                 alt="<?= __('Logo') ?>" width="100">
        </div>
    <?php endif; ?>

    <!--    Page Title Area-->
    <div id="mpbm-page-title">
        <h1 class="mpbm-text" style="margin-bottom: 0"><?= $data['[maintenance_title]'] ?></h1>
    </div>

    <!--    Page Description Area-->
    <div id="mpbm-page-description">
        <h3 class="mpbm-text"><?= $data['[maintenance_description]'] ?></h3>
    </div>

    <!--    Clock area-->
    <?php if ($data['[clock_enabled]']) : ?>
        <div id="mpbm-clock">
            <?= $block->getClockBlock() ?>
        </div>
    <?php endif; ?>

    <!--    Progress Area-->
    <?php if ($data['[maintenance_progress_enabled]']): ?>
        <div id="mpbm-progress-bar">
            <div class="row">
                <div class="mp-md-6">
                    <div class="progress mp-md-3">
                        <div class="progress-bar" role="progressbar"
                             aria-valuenow="<?= $data['[maintenance_progress_value]'] ?>"
                             aria-valuemin="0"
                             aria-valuemax="100"><?= $data['[maintenance_progress_value]'] ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php endif; ?>

    <!--    Subscribe area-->
    <?php if ($data['[subscribe_type]'] !== 'none') : ?>
        <?php $subscribeLabel = $data['[subscribe_label]'] ?>
        <?php $subscribeLabelColor = $data['[subscribe_label_color]'] ?>
        <?php if ($data['[subscribe_type]'] === 'email_form') : ?>
            <div id="mpbm-subscribe">
                <?php if ($subscribeLabel): ?>
                    <h4 style="color: <?= $subscribeLabelColor ?>"><?= $subscribeLabel ?></h4>
                <?php endif; ?>
                <?= $block->getSubscribeBlock() ?>
            </div>
        <?php elseif ($data['[subscribe_type]'] === 'register_form') : ?>
            <div id="mpbm-register">
                <?php if ($subscribeLabel): ?>
                    <h4 style="color: <?= $subscribeLabelColor ?>"><?= $subscribeLabel ?></h4>
                <?php endif; ?>
                <?= $block->getRegisterBlock() ?>
            </div>
        <?php endif; ?>
    <?php endif; ?>

    <!--    Social area-->
    <?php if ($data['[social_enabled]']): ?>
        <div id="mpbm-social-contact">
            <div id="mpbm-social-label" style="display: inline-block">
                <p><?= $data['[social_label]'] ?></p>
            </div>
            <?php foreach ($block->getSocialList() as $value) : ?>
                <?php if ($value['link']) : ?>
                    <div class="mpbm-social-box" style="display: inline-block; vertical-align: middle">
                        <a href="<?= $value['link'] ?>" target="_blank">
                            <img src="<?= $value['img'] ?>" alt="<?= __('Social Logo') ?>" width="20">
                        </a>
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <?php if ($block->getBlockCms()) : ?>
        <div id="mpbm-footer-block">
            <?= $block->getBlockCms() ?>
        </div>
    <?php endif; ?>
</div>

<style>
    .mpbm-text {
        color: <?= $data['[maintenance_color]'] ?>;
    }

    #mpbm-social-label {
        color: <?= $data['[social_label_color]'] ?>;
    }

    <?php if ($data['[clock_template]'] === 'stack') : ?>
    .stack-txt1 {
        background: <?= $data['[clock_inner_color]'] ?>;
    }

    <?php endif; ?>

    .progress-bar {
        height: 45px;
        font-size: 100%;
        font-weight: bold;
        border-radius: 50px;
        line-height: 45px;
        color: <?= $data['[maintenance_progress_label_color]'] ?>;
        background-color: <?= $data['[maintenance_progress_bar_color]'] ?>;
        width: 0;
    }
</style>

<?php if ($data['[subscribe_type]'] !== 'none') : ?>
    <script>
        require([
            'jquery'
        ], function ($) {
            var subBtn = $('.action.primary span');
            subBtn.text("<?= $data['[button_label]'] ?>").css("color", "<?= $data['[button_label_color]'] ?>");
            $('.action.primary').css("background", "<?= $data['[button_background_color]'] ?>");
        });
    </script>
<?php endif; ?>

<script type="text/x-magento-init">
    {
        ".mpbm-wrapper": {
            "maintenancePreview": {
                "progressLabel": "<?= $data['[maintenance_progress_label]'] ?>"
            }
        }
    }


</script>