<?php $data = $block->getFormData(); ?>
<!--Multiple Image Background-->
<?php if ($data['[comingsoon_background]'] === 'multiple_images'): ?>
    <?php $listImagesUrl = implode(',', $block->getMultipleImagesUrl('comingsoon_background_multi_image')); ?>
    <style>
        .mpbettermaintenance-comingsoon-preview {
            background-repeat: no-repeat;
            background-size: cover;
            transition-delay: 2s;
        }
    </style>
    <script>
        require([
            'jquery'
        ], function ($) {
            var images    = '<?= $listImagesUrl ?>';
            images        = images.split(',');
            var nextImage = 0;
            doSlideshow();

            function doSlideshow () {
                if (nextImage >= images.length) {
                    nextImage = 0;
                }
                $('.mpbettermaintenance-comingsoon-preview')
                .fadeIn('slow', function () {
                    setTimeout(doSlideshow, 5000);
                }).css('background-image', 'url("' + images[nextImage++] + '")');
            }
        });
    </script>
<?php endif; ?>

<!--Single Image Background-->
<?php if ($data['[comingsoon_background]'] === 'image'
    && $block->getImageUrl($data['[comingsoon_background_image]'])): ?>
    <style>
        .mpbettermaintenance-comingsoon-preview {
            background-image: url("<?= $block->getImageUrl($data['[comingsoon_background_image]']) ?>");
            background-repeat: no-repeat;
            background-size: cover;
        }
    </style>
<?php endif; ?>

<!--Video Background-->
<?php if ($data['[comingsoon_background]'] === 'video'
    && $block->getVideoUrl($data['[comingsoon_background_video]'])): ?>
    <video autoplay muted loop id="mpbm-video">
        <source src="<?= $block->getVideoUrl($data['[comingsoon_background_video]']) ?>"
                type="video/mp4">
    </video>
<?php endif; ?>
<div id="mpbm-<?= $data['[comingsoon_layout]'] ?>-column" class="mpbm-preview-wrapper">
    <?php if (!empty($data['[comingsoon_logo]'])): ?>
        <div id="mpbm-logo">
            <img src="<?= $block->getLogo($data['[comingsoon_logo]']) ?>"
                 alt="<?= __('Logo') ?>" width="100">
        </div>
    <?php endif; ?>

    <!--    Page Title Area-->
    <div id="mpbm-page-title">
        <h1 class="mpbm-text" style="margin-bottom: 0"><?= $data['[comingsoon_title]'] ?></h1>
    </div>

    <!--    Page Description Area-->
    <div id="mpbm-page-description">
        <h3 class="mpbm-text"><?= $data['[comingsoon_description]'] ?></h3>
    </div>

    <!--    Clock area-->
    <?php if ($data['[clock_enabled]']) : ?>
        <div id="mpbm-clock">
            <?= $block->getClockBlock() ?>
        </div>
    <?php endif; ?>

    <!--    Subscribe area-->
    <?php if ($data['[subscribe_type]'] !== 'none') : ?>
        <?php $subscribeLabel = $data['[subscribe_label]'] ?>
        <?php $subscribeLabelColor = $data['[subscribe_label_color]'] ?>
        <?php if ($data['[subscribe_type]'] === 'email_form') : ?>
            <div id="mpbm-subscribe">
                <?php if ($subscribeLabel): ?>
                    <h4 style="color: <?= $subscribeLabelColor ?>"><?= $subscribeLabel ?></h4>
                <?php endif; ?>
                <?= $block->getSubscribeBlock() ?>
            </div>
        <?php elseif ($data['[subscribe_type]'] === 'register_form') : ?>
            <div id="mpbm-register">
                <?php if ($subscribeLabel): ?>
                    <h4 style="color: <?= $subscribeLabelColor ?>"><?= $subscribeLabel ?></h4>
                <?php endif; ?>
                <?= $block->getRegisterBlock() ?>
            </div>
        <?php endif; ?>
    <?php endif; ?>

    <!--    Social area-->
    <?php if ($data['[social_enabled]']): ?>
        <div id="mpbm-social-contact">
            <div id="mpbm-social-label" style="display: inline-block">
                <p><?= $data['[social_label]'] ?></p>
            </div>
            <?php foreach ($block->getSocialList() as $value) : ?>
                <?php if ($value['link']) : ?>
                    <div class="mpbm-social-box" style="display: inline-block; vertical-align: middle">
                        <a href="<?= $value['link'] ?>" target="_blank">
                            <img src="<?= $value['img'] ?>" alt="<?= __('Social Logo') ?>" width="20">
                        </a>
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <?php if ($block->getBlockCms()) : ?>
        <div id="mpbm-footer-block">
            <?= $block->getBlockCms() ?>
        </div>
    <?php endif; ?>
</div>

<style>
    .mpbm-text {
        color: <?= $data['[comingsoon_color]'] ?>;
    }

    #mpbm-social-label {
        color: <?= $data['[social_label_color]'] ?>;
    }

    <?php if ($data['[clock_template]'] === 'stack') : ?>
    .stack-txt1 {
        background: <?= $data['[clock_inner_color]'] ?>;
    }
    <?php endif; ?>
</style>

<?php if ($data['[subscribe_type]'] !== 'none') : ?>
    <script>
        require([
            'jquery'
        ], function ($) {
            var subBtn = $('.action.primary span');
            subBtn.text("<?= $data['[button_label]'] ?>").css("color", "<?= $data['[button_label_color]'] ?>");
            $('.action.primary').css("background", "<?= $data['[button_background_color]'] ?>");
        });
    </script>
<?php endif; ?>

<script type="text/x-magento-init">
    {
        ".mpbm-wrapper": {
            "maintenancePreview": {}
        }
    }

</script>